networknt/light-codegen

- codegen-cli/src/main/java/com/networknt/codegen/Cli.java
> Adding help option and descriptions to codegen-cli parameters.

- codegen-web/view/src/AppActions.js
generate request schema sent to api service was incorrect and was missing a key
> fix request schema for generate request

- codegen-web/view/package-lock.json
> Fix: Bump version of moment dependency

- codegen-web/src/main/java/com/networknt/codegen/handler/GeneratorServiceHandler.java
- codegen-web/src/main/resources/config/cors.yml
- codegen-web/src/main/resources/config/secret.yml
- codegen-web/src/main/resources/config/security.yml
- codegen-web/src/main/resources/config/server.yml
- codegen-web/src/test/java/com/networknt/codegen/handler/GeneratorServiceHandlerTest.java
- codegen-web/view/src/AppConstants.js
- codegen-web/view/src/AppServices.js
- codegen-web/view/src/app-content/generate-step/GenerateStep.js
This change will support returning zip's for download directly to the client browser.
Please let me know if there's anything I should change.
In regards to: #112 
Thanks
> feat(zip): Returning zip file for download from codegen-web generator

- CONTRIBUTING.md
- light-rest-4j/src/main/java/com/networknt/codegen/rest/OpenApiGenerator.java
- light-rest-4j/src/main/resources/templates/rest/project.rocker.raw
- Added missing CONTRIBUTING.md referenced from README.md 
- Fixes #147 Generated .project file is not a valid XML
- Fixes #146 Code generation fails without "securitySchemes" section in openapi model
>  Fixes #147,  Fixes #146

- light-rest-4j/src/main/resources/templates/rest/openapi/handlerYml.rocker.raw
- light-rest-4j/src/main/resources/templates/rest/swagger/handlerYml.rocker.raw
-comment out dump handler in generated handler.yml
-make generated dump option in handlerYml.rocker.raw consist between openapi and swagger 
-related to: https://github.com/networknt/light-4j/issues/23
> comment out dump handler in generated handler.yml

- light-eventuate-4j/src/main/resources/templates/eventuate/hybrid/logback.rocker.raw
- light-eventuate-4j/src/main/resources/templates/eventuate/rest/logback.rocker.raw
- light-graphql-4j/src/main/resources/templates/graphql/logback.rocker.raw
- light-hybrid-4j/src/main/resources/templates/hybrid/logback.rocker.raw
- light-rest-4j/src/main/resources/templates.restkotlin/logback.rocker.raw
- light-rest-4j/src/main/resources/templates/rest/logback.rocker.raw
- light-rest-4j/src/main/resources/templates/rest/openapi/pom.xml.rocker.raw
#242 Make pom.xml developer friendly by seggragating shading, javadoc, sources into a non-default profile
> Make pom.xml developer friendly by seggragating shading, javadoc, sources into a non-default profile

- light-rest-4j/src/main/java/com/networknt/codegen/rest/OpenApiGenerator.java
- light-rest-4j/src/main/resources/templates/rest/pojo.rocker.raw
- light-rest-4j/src/test/java/com/networknt/codegen/OpenApiArrayReferenceGeneratorTest.java
- light-rest-4j/src/test/resources/array_ref-oa3.json
- pom.xml
Reverts networknt/light-codegen#252
> Revert "#158 binary format string - fix the handling of binary and byte forma…"

- light-rest-4j/src/main/resources/templates/rest/handler.rocker.raw
related issue:https://github.com/networknt/light-codegen/issues/284
> fixed NPE for param description feature

- light-rest-4j/src/main/java/com/networknt/codegen/rest/OpenApiGenerator.java
- light-rest-4j/src/main/resources/templates/rest/openapi/config.rocker.raw
related issue: https://github.com/networknt/light-codegen/issues/296
> Generate decryption methods

- light-rest-4j/src/main/resources/templates/rest/openapiSecurity.yml.rocker.raw
change the openapi-security.yml raw file entry name.
> fixes #378

- light-rest-4j/src/main/java/com/networknt/codegen/rest/OpenApiGenerator.java
- light-rest-4j/src/main/java/com/networknt/codegen/rest/SwaggerGenerator.java
Related issue: https://github.com/networknt/light-codegen/issues/396
> Fix swagger enum description

- light-rest-4j/src/main/java/com/networknt/codegen/rest/OpenApiGenerator.java
- light-rest-4j/src/main/java/com/networknt/codegen/rest/SwaggerGenerator.java
The PR 400 cherry-pick failed so I have to manually merge the change from 1.6.x to master. I have tested the generated swagger and openapi projects and they are building fine.
> fixes #396 manually sync PR 400 from 1.6.x to master

- .gitignore
Adding bin folder to gitignore
> Adding bin folder to gitignore

- light-rest-4j/src/main/resources/templates/rest/enumInline.rocker.raw
- added json property for enums
- resolves #557
> fix #557 json property in enum

- light-rest-4j/src/main/resources/templates/rest/testServer.rocker.raw
resolves #560 
- added shutdown hook for jvm instead of clean it every time.
> fix #560 tests with gradle

- light-rest-4j/src/main/java/com/networknt/codegen/rest/OpenApiGenerator.java
resolves #564 
- check if security is empty before get it
> fix #564 avoid security list empty

- light-rest-4j/src/main/resources/templates/rest/openapi/handlerTest.rocker.raw
- light-rest-4j/src/main/resources/templates/rest/openapi/pom.xml.rocker.raw
- light-rest-4j/src/main/resources/templates/rest/testServer.rocker.raw
change the junit from junit4 to junit 5
>  change the 1.6.x branch codegen junit test case to use junit5+

- light-rest-4j/src/main/resources/templates/rest/openapi/pom.xml.rocker.raw
Add the missed version property of fastscanner.
> add the missed version property of fastscanner

- light-rest-4j/src/main/java/com/networknt/codegen/rest/OpenApiGenerator.java
- light-rest-4j/src/main/java/com/networknt/codegen/rest/OpenApiLightGenerator.java
- light-rest-4j/src/main/resources/templates/rest/handlerSingle.rocker.raw
- light-rest-4j/src/main/resources/templates/rest/handlerTest.rocker.raw
fix issue 635
fix the test class error
> fixes #635
